Serving aliases
avrae/avrae pull request #1629
Opened 2021-10-02 14:50 UTC by driesceuppens

### Summary
This PR adds the option to `!alias serve` an alias to toggle it to be an active server alias, this should work for workshop aliases too but I can't test that part.

### Checklist

#### PR Type

- [x] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [x] I have updated the documentation to reflect the changes.

2021-11-24 19:23 UTC, zhudotexe requested changes

2021-11-24 19:23 UTC, zhudotexe commented on cogsmisc/customization.py
> +        personal_obj, collection = await get_selection(ctx, choices)
it might be worth using `aliasing.helpers.get_personal_*_named` here

2021-11-24 19:23 UTC, zhudotexe commented on cogsmisc/customization.py
> +        else:  # We're working with a workshop collection, easy peasy
since this is subscribing an entire collection instead of adding a single alias, it may be worth adding a confirmation here

2021-11-24 19:23 UTC, zhudotexe commented on cogsmisc/customization.py
> +            personal_obj.set_server_active(ctx)
`WorkshopAlias`/`WorkshopSnippet.set_server_active` does not exist, did you mean `WorkshopCollection`'s method?

2021-11-24 19:23 UTC, zhudotexe commented on cogsmisc/customization.py
> +            embed.title = f"Subscribed to {the_collection.name}"
`the_collection` is probably referencing the wrong variable here

2021-11-24 19:23 UTC, zhudotexe commented on cogsmisc/customization.py
> +        await server_obj.commit(ctx.bot.mdb)
while `server_obj` is guaranteed to be defined here because of the return, this code flow is difficult to follow

2021-11-25 23:57 UTC, driesceuppens commented on cogsmisc/customization.py
> +                help=f'Sets an alias as a server alias or subscribes the server to a workshop collection.')(self.serve)
I addressed all the things you pointed out in the most recent commit, hopefully, it will be better this time.

2021-12-01 19:53 UTC, merged